import { Router } from "express";
import { authRouter } from "./auth.routes";
import { userRouter } from "./user.routes";
import { staffRouter } from "./staff.routes";
import { studentRouter } from "./student.routes";
import { parentRouter } from "./parent.routes";
import { campusRouter, departmentRouter } from "./structure.routes";
import { programmeRouter, subjectRouter } from "./curriculum.routes";
import { classRouter } from "./class.routes";
import { enrolmentRouter } from "./enrolment.routes";
import { resultRouter } from "./result.routes";
import { documentRouter } from "./document.routes";
import { feeRouter } from "./fee.routes";
import { paymentRouter } from "./payment.routes";
import { announcementRouter } from "./announcement.routes";
import { messageRouter } from "./message.routes";
import { notificationRouter } from "./notification.routes";
import { attendanceRouter } from "./attendance.routes";
import { timetableRouter } from "./timetable.routes";
import { reportRouter } from "./report.routes";
import { auditLogRouter, adminSettingsRouter } from "./admin.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/students", studentRouter);
apiRouter.use("/parents", parentRouter);
apiRouter.use("/campuses", campusRouter);
apiRouter.use("/departments", departmentRouter);
apiRouter.use("/programmes", programmeRouter);
apiRouter.use("/subjects", subjectRouter);
apiRouter.use("/classes", classRouter);
apiRouter.use("/enrolments", enrolmentRouter);
apiRouter.use("/results", resultRouter);
apiRouter.use("/documents", documentRouter);
apiRouter.use("/fees", feeRouter);
apiRouter.use("/payments", paymentRouter);
apiRouter.use("/announcements", announcementRouter);
apiRouter.use("/messages", messageRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/timetables", timetableRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/audit-logs", auditLogRouter);
apiRouter.use("/admin", adminSettingsRouter);
